services:
  # Redis (キューシステム用)
  redis:
    image: redis:7-alpine
    container_name: fuji-calendar-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  # アプリケーションサーバー
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.simple
    container_name: fuji-calendar-app
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_PATH=/app/data/fuji-calendar.db
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - REFRESH_SECRET=${REFRESH_SECRET:-your-super-secret-refresh-key-change-in-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_FILE_LOGGING=${ENABLE_FILE_LOGGING:-true}
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
    driver: local
  app_data:
    driver: local
  app_logs:
    driver: local

networks:
  default:
    name: fuji-calendar-network