services:
  # フロントエンド（nginx + 静的ファイル配信）
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: fuji_calendar_frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./ssl:/etc/nginx/ssl:ro  # SSL 証明書用（オプション）
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - fuji_calendar_network

  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: fuji_calendar_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"  # メンテナンス用外部アクセス対応
    environment:
      POSTGRES_DB: ${DB_NAME:-fuji_calendar}
      POSTGRES_USER: ${DB_USER:-fuji_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password_change_me}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: Asia/Tokyo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-fuji_user} -d ${DB_NAME:-fuji_calendar}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - fuji_calendar_network

  # Redis (キューシステム用・内部アクセスのみ)
  redis:
    image: redis:7-alpine
    container_name: fuji_calendar_redis
    restart: unless-stopped
    expose:
      - "6379"  # 外部ポート公開なし（Docker 内部のみアクセス可）
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - fuji_calendar_network

  # バックエンド API（モノレポ構成）
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.simple
    container_name: fuji_calendar_backend
    restart: unless-stopped
    expose:
      - "${PORT:-3000}"
    # リソース制限でパフォーマンス安定化
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3000}
      # PostgreSQL 接続設定（Prisma 対応）
      DATABASE_URL: postgresql://${DB_USER:-fuji_user}:${DB_PASSWORD:-FujiAdmin2025!}@postgres:5432/${DB_NAME:-fuji_calendar}
      # Redis 設定
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # JWT 設定
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      REFRESH_SECRET: ${REFRESH_SECRET:-your-super-secret-refresh-key-change-in-production}
      # ログ設定
      LOG_LEVEL: ${LOG_LEVEL:-info}
      ENABLE_FILE_LOGGING: ${ENABLE_FILE_LOGGING:-true}
      LOG_DIR: /app/logs
      # フロントエンド設定
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost}
      # タイムゾーン
      TZ: Asia/Tokyo
      # ワーカー設定（バックエンドでも低負荷モード）
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-1}
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fuji_calendar_network

  # ワーカー（バックグラウンドジョブ処理）
  worker:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.simple
    container_name: fuji_calendar_worker
    restart: unless-stopped
    command: ["npm", "run", "start:worker"]
    # ワーカー用リソース制限（より少なく）
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    environment:
      NODE_ENV: production
      # PostgreSQL 接続設定（Prisma 対応）
      DATABASE_URL: postgresql://${DB_USER:-fuji_user}:${DB_PASSWORD:-FujiAdmin2025!}@postgres:5432/${DB_NAME:-fuji_calendar}
      # Redis 設定
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # ログ設定
      LOG_LEVEL: ${LOG_LEVEL:-info}
      ENABLE_FILE_LOGGING: ${ENABLE_FILE_LOGGING:-true}
      LOG_DIR: /app/logs
      # タイムゾーン
      TZ: Asia/Tokyo
      # ワーカー設定（低負荷モード）
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-1}
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "-f", "worker"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - fuji_calendar_network

volumes: {}

networks:
  fuji_calendar_network:
    driver: bridge
