version: '3.8'

services:
  # Nginx (リバースプロキシ + 静的ファイル配信)
  nginx:
    image: nginx:alpine
    container_name: fuji-calendar-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - app_static:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl:ro  # SSL証明書用（オプション）
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  # バックエンドAPI
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fuji-calendar-backend
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_PATH=/app/data/fuji-calendar.db
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - REFRESH_SECRET=${REFRESH_SECRET:-your-super-secret-refresh-key-change-in-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_FILE_LOGGING=${ENABLE_FILE_LOGGING:-true}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - app_static:/app/dist/client  # ビルド済み静的ファイルを共有
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis (キューシステム用)
  redis:
    image: redis:7-alpine
    container_name: fuji-calendar-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  app_static:
    driver: local

networks:
  default:
    name: fuji-calendar-network