services:
  # PostgreSQL (Docker 内部アクセスのみ)
  postgres:
    image: postgres:15-alpine
    container_name: fuji_calendar_postgres
    restart: unless-stopped
    expose:
      - "5432"  # Docker 内部のみアクセス可
    environment:
      POSTGRES_DB: ${DB_NAME:-fuji_calendar}
      POSTGRES_USER: ${DB_USER:-fuji_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-prod_password_change_me}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: Asia/Tokyo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-fuji_user} -d ${DB_NAME:-fuji_calendar}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - fuji_calendar_network

  # Redis (キューシステム用・内部アクセスのみ)
  redis:
    image: redis:7-alpine
    container_name: fuji_calendar_redis
    restart: unless-stopped
    expose:
      - "6379"  # 外部ポート公開なし（Docker 内部のみアクセス可）
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - fuji_calendar_network

  # Nginx (リバースプロキシ + 静的ファイル配信)
  nginx:
    image: nginx:alpine
    container_name: fuji_calendar_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./apps/client/dist:/usr/share/nginx/html:ro  # モノレポ構成の静的ファイル
      - ./ssl:/etc/nginx/ssl:ro  # SSL 証明書用（オプション）
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - fuji_calendar_network

  # バックエンド API（モノレポ構成）
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.monolith
    container_name: fuji_calendar_backend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      # PostgreSQL 接続設定（Prisma 対応）
      DATABASE_URL: postgresql://${DB_USER:-fuji_user}:${DB_PASSWORD:-prod_password_change_me}@postgres:5432/${DB_NAME:-fuji_calendar}
      # Redis 設定
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # JWT 設定
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      REFRESH_SECRET: ${REFRESH_SECRET:-your-super-secret-refresh-key-change-in-production}
      # ログ設定
      LOG_LEVEL: ${LOG_LEVEL:-info}
      ENABLE_FILE_LOGGING: ${ENABLE_FILE_LOGGING:-true}
      LOG_DIR: /app/logs
      # フロントエンド設定
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost}
      # タイムゾーン
      TZ: Asia/Tokyo
    volumes:
      - ./logs:/app/logs
      - ./apps/client/dist:/app/apps/client/dist  # モノレポ構成の静的ファイル
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fuji_calendar_network

  # ワーカー（バックグラウンドジョブ処理）
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.monolith
    container_name: fuji_calendar_worker
    restart: unless-stopped
    command: ["npm", "run", "start:worker"]
    environment:
      NODE_ENV: production
      # PostgreSQL 接続設定（Prisma 対応）
      DATABASE_URL: postgresql://${DB_USER:-fuji_user}:${DB_PASSWORD:-prod_password_change_me}@postgres:5432/${DB_NAME:-fuji_calendar}
      # Redis 設定
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # ログ設定
      LOG_LEVEL: ${LOG_LEVEL:-info}
      ENABLE_FILE_LOGGING: ${ENABLE_FILE_LOGGING:-true}
      LOG_DIR: /app/logs
      # タイムゾーン
      TZ: Asia/Tokyo
      # ワーカー設定
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-5}
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "-f", "worker"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - fuji_calendar_network

volumes: {}

networks:
  fuji_calendar_network:
    driver: bridge
