services:
  # Redis (開発用)
  redis:
    image: redis:7-alpine
    container_name: fuji-calendar-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes

  # 開発サーバー (ホットリロード対応)
  app-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: fuji-calendar-app-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_PATH=/app/data/fuji-calendar-dev.db
      - JWT_SECRET=dev-jwt-secret-not-for-production
      - REFRESH_SECRET=dev-refresh-secret-not-for-production
      - LOG_LEVEL=debug
      - ENABLE_FILE_LOGGING=false
    volumes:
      - .:/app
      - /app/node_modules
      - app_dev_data:/app/data
    depends_on:
      - redis
    working_dir: /app
    command: npm run dev

volumes:
  redis_dev_data:
    driver: local
  app_dev_data:
    driver: local

networks:
  default:
    name: fuji-calendar-dev-network